steps:
# [Enable Cached Docker Build] 
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --cache=true
  - --cache-ttl=6h

# [Enable GCP APIs]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
    - 'services'
    - 'enable'
    - 'serviceusage.googleapis.com'
    - 'iam.googleapis.com'
    - 'cloudresourcemanager.googleapis.com'
    - 'artifactregistry.googleapis.com'
    - 'cloudfunctions.googleapis.com'
    - 'firestore.googleapis.com'
    - 'run.googleapis.com'

# [GCS For Terraform Backend]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        gsutil mb gs://${PROJECT_ID}-tfstate || exit 0
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gsutil'
  args:
    - 'versioning'
    - 'set'
    - 'on'
    - 'gs://${PROJECT_ID}-tfstate'

# [terraform]
- name: 'hashicorp/terraform:0.12.29'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd terraform
        terraform init -backend-config="bucket=${PROJECT_ID}-tfstate" -backend-config="prefix=terraform/state"
        echo "=================================================="
        echo " terraform init finished" 
        echo "=================================================="

- name: 'hashicorp/terraform:0.12.29'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd terraform
        terraform plan -var project_id=${PROJECT_ID} -var zone=${_ZONE} -var region=${_REGION} -var app=cloudrun -var env=dev 
        echo "=================================================="
        echo " terraform plan finished" 
        echo "=================================================="

- name: 'hashicorp/terraform:0.12.29'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd terraform
        terraform apply -auto-approve -var project_id=${PROJECT_ID} -var zone=${_ZONE} -var region=${_REGION} -var app=cloudrun -var env=dev 
        echo "=================================================="
        echo " terraform apply finished" 
        echo "=================================================="


# [web]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy' 
    - 'helloworld'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld'
    - '--set-env-vars'
    - 'name=gamma'
    - '--allow-unauthenticated'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-east1'

# [processor]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'processor'
    - '--region'
    - 'us-east1'
    - '--trigger-topic'
    - 'cloudrun-dev-pub-msg-topic'
    - '--runtime'
    - 'nodejs10'
    - '--entry-point'
    - 'process'
    - '--source'
    - 'processor'

substitutions:
  _REGION: us-east1
  _ZONE: us-east1-a
   
images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld'
