steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy' 
    - 'helloworld'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld'
    - '--set-env-vars'
    - 'name=gamma'
    - 'allow-unauthenticated'
images: ['us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld']
