steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy' 
    - 'helloworld'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld'
    - '--set-env-vars'
    - 'name=gamma'
    - '--allow-unauthenticated'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-east1'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'processor'
    - '--region'
    - 'us-east1'
    - '--trigger-topic'
    - 'cloudrun-dev-pub-msg-topic'
    - '--runtime'
    - 'nodejs10'
    - '--entry-point'
    - 'process'
    - '--source'
    - 'processor'

images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudrun-dev-repository/helloworld'
