steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy' 
    - 'helloworld'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld'
    - '--set-env-vars'
    - 'name=gamma'
    - '--allow-unauthenticated'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-east1'
images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/docker-repo/helloworld:$COMMIT_SHA'
